name: CI

on: [push, pull_request]

env:
  DATABASE_URL: "https://fake.com"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Deps
        uses: npm install

      - name: Typecheck
        uses: npm run typecheck

      - name: Lint
        uses: npm run lint

      - name: Print Env Vars
        run: echo $MY_ENV_VAR
